# Generated by Django 5.0.3 on 2026-04-24 18:42

import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantBalance',
            fields=[
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='balance', serialize=False, to='payouts.merchant')),
                ('available_balance', models.BigIntegerField(default=0, help_text='Available balance in paise')),
                ('held_balance', models.BigIntegerField(default=0, help_text='Held balance in paise')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(help_text='Amount in paise')),
                ('entry_type', models.CharField(choices=[('CREDIT', 'Credit'), ('HOLD', 'Hold'), ('HOLD_RELEASE', 'Hold Release'), ('PAYOUT_DEBIT', 'Payout Debit')], max_length=20)),
                ('payout_id', models.UUIDField(blank=True, help_text='Reference to the related payout, if any', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='payouts.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('key', models.UUIDField(primary_key=True, serialize=False)),
                ('response_status', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payouts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=50)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='payouts.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(help_text='Amount in paise')),
                ('state', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50, protected=True)),
                ('idempotency_key', models.UUIDField()),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payouts.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payouts.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('merchant', 'key'), name='unique_idempotency_record'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('merchant', 'idempotency_key'), name='unique_merchant_idempotency_key'),
        ),
    ]
